import { run as runEj01 } from './ejercicios/ej01';
import { run as runEj02 } from './ejercicios/ej02';
import { run as runEj03 } from './ejercicios/ej03';
import { run as runEj04 } from './ejercicios/ej04';
import { run as runEj05 } from './ejercicios/ej05';
import { crearFruta } from './ejercicios/ej06';
import { crearNinja} from './ejercicios/ej07';
import { run as runEj10 } from './ejercicios/ej10';
import { run as runEj11 } from './ejercicios/ej11';

console.log('========== Ejercicios ==========');
//runEj01();
//runEj02();
//runEj03();
//runEj04();
//runEj05();
//crearFruta();
//crearNinja();
//runEj10();
runEj11();